### ISSUE TITLE
TypeError: Parameters to generic types must be types. Got <BaseTypes.PhoneNumber: 5000>.

### ISSUE THREAD

**Issue by allewwaly** [PadishahIII/RFGuess#2]
C:\Users\john\RFGuess>python main.py
Traceback (most recent call last):
  File "C:\Users\john\RFGuess\main.py", line 2, in <module>
    from ui.slots import *
  File "C:\Users\john\RFGuess\ui\slots.py", line 18, in <module>
    from Generators.GeneralPIIGenerators import *
  File "C:\Users\john\RFGuess\Generators\GeneralPIIGenerators.py", line 4, in <module>
    from Parser.GeneralPIIParsers import *
  File "C:\Users\john\RFGuess\Parser\GeneralPIIParsers.py", line 3, in <module>
    from Parser.PIIParsers import *
  File "C:\Users\john\RFGuess\Parser\PIIParsers.py", line 608, in <module>
    class PIIToTagParser:
  File "C:\Users\john\RFGuess\Parser\PIIParsers.py", line 750, in PIIToTagParser
    def parsePhoneNumToTagDict(cls, phoneNum: str) -> typing.Dict[BasicTypes.PIIType.BaseTypes.PhoneNumber, list]:
  File "C:\Programs\Python\Python39\lib\typing.py", line 275, in inner
    return func(*args, **kwds)
  File "C:\Programs\Python\Python39\lib\typing.py", line 827, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Programs\Python\Python39\lib\typing.py", line 827, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Programs\Python\Python39\lib\typing.py", line 164, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got <BaseTypes.PhoneNumber: 5000>.

**Comment by PadishahIII** [comment]
Hi, it seems like you are using a python interpreter older than 3.9, just move to 3.11 and this problem will disappear.
